import { serve } from "bun";
import index from "./index.html";

/**
 * Pre-load transaction data files for the presentation
 * These files are generated by generate_financial_data.ts in the parent directory
 */
let transactionsJson: string | null = null;
let transactionsCsv: string | null = null;

async function loadTransactionData(): Promise<void> {
  try {
    const jsonFile = Bun.file("./transactions.json");
    if (await jsonFile.exists()) {
      transactionsJson = await jsonFile.text();
      console.log("✅ Loaded transactions.json");
    } else {
      console.warn("⚠️ transactions.json not found - run 'bun generate_financial_data.ts' first");
    }
  } catch (error) {
    console.error("❌ Error loading transactions.json:", error);
  }

  try {
    const csvFile = Bun.file("./transactions.csv");
    if (await csvFile.exists()) {
      transactionsCsv = await csvFile.text();
      console.log("✅ Loaded transactions.csv");
    } else {
      console.warn("⚠️ transactions.csv not found - run 'bun generate_financial_data.ts' first");
    }
  } catch (error) {
    console.error("❌ Error loading transactions.csv:", error);
  }
}

// Load transaction data before starting the server
await loadTransactionData();

const server = serve({
  routes: {
    // Serve index.html for all unmatched routes.
    "/*": index,

    // Serve pre-loaded transaction data for the presentation
    "/api/data/transactions.json": {
      GET() {
        if (!transactionsJson) {
          return new Response(
            JSON.stringify({ error: "Transaction JSON data not loaded" }),
            { status: 404, headers: { "Content-Type": "application/json" } }
          );
        }
        return new Response(transactionsJson, {
          headers: { "Content-Type": "application/json" },
        });
      },
    },

    "/api/data/transactions.csv": {
      GET() {
        if (!transactionsCsv) {
          return new Response("Transaction CSV data not loaded", {
            status: 404,
            headers: { "Content-Type": "text/plain" },
          });
        }
        return new Response(transactionsCsv, {
          headers: { "Content-Type": "text/csv" },
        });
      },
    },

    // Check if transaction data is available
    "/api/data/status": {
      GET() {
        return Response.json({
          json: transactionsJson !== null,
          csv: transactionsCsv !== null,
          jsonSize: transactionsJson?.length ?? 0,
          csvSize: transactionsCsv?.length ?? 0,
        });
      },
    },
  },

  development: process.env.NODE_ENV !== "production" && {
    // Enable browser hot reloading in development
    hmr: true,

    // Echo console logs from the browser to the server
    console: true,
  },
});

console.log(`🚀 Server running at ${server.url}`);
